# Generated by Django 5.2.5 on 2026-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
